### PR TITLE
Migrate to bevy 0.13

### PR DESCRIPTION
**Pull request by mogambro**
Hello!

Two problems with the migration:

1) I can't find the correct bevy feature combination to make it work with minimal features. As you can see in the Cargo.toml I tried and actually tried a lot of combinations, but without all of bevy I couldn't get the StandardMaterial to work and it was pink instead of black

2) I can't get the uv_mapping example to work (no git lfs problem, I have the texture), it simple doesn't appear.

Still wanted to open this, because maybe it's useful for someone and maybe someone will jump in to fix the problems mentioned

### CODE REVIEW

**Comment by bonsairobo** [comment]
@nerdachse I think the pink texture issue is a result of missing the proper set of features to support compressed textures. I believe you need the features I added here:

https://github.com/bonsairobo/smooth-bevy-cameras/commit/171521759169ada15d83c3ebec02771af20f5552

**Comment by mogambro** [comment]
Just a headsup: I am currently on vacation and will try this out once back in a few weeks :)

For me the example doesn't show at all though, not a pink texture

**Comment by mogambro** [comment]
Took me a while, but it's now targeting 0.13 - I still can't get the textures to work though, even if I have a valid file on my PC (I can open it just fine) and everything seems to load in bevy.

**Comment by bonsairobo** [comment]
Going to merge this into a local `bevy-0.13` branch and see if I can fix the texturing issue.

**Pull request merged**
